// Master list of Indian stocks for search functionality
const STOCKS_LIST = [
  { name: "RELIANCE", fullName: "Reliance Industries Ltd", sector: "Energy" },
  { name: "TCS", fullName: "Tata Consultancy Services Ltd", sector: "IT" },
  { name: "HDFCBANK", fullName: "HDFC Bank Ltd", sector: "Banking" },
  { name: "INFY", fullName: "Infosys Ltd", sector: "IT" },
  { name: "HINDUNILVR", fullName: "Hindustan Unilever Ltd", sector: "FMCG" },
  { name: "ICICIBANK", fullName: "ICICI Bank Ltd", sector: "Banking" },
  { name: "SBIN", fullName: "State Bank of India", sector: "Banking" },
  { name: "BHARTIARTL", fullName: "Bharti Airtel Ltd", sector: "Telecom" },
  { name: "ITC", fullName: "ITC Ltd", sector: "FMCG" },
  { name: "KOTAKBANK", fullName: "Kotak Mahindra Bank Ltd", sector: "Banking" },
  { name: "LT", fullName: "Larsen & Toubro Ltd", sector: "Infrastructure" },
  { name: "AXISBANK", fullName: "Axis Bank Ltd", sector: "Banking" },
  { name: "WIPRO", fullName: "Wipro Ltd", sector: "IT" },
  { name: "BAJFINANCE", fullName: "Bajaj Finance Ltd", sector: "Finance" },
  { name: "ASIANPAINT", fullName: "Asian Paints Ltd", sector: "Paints" },
  { name: "MARUTI", fullName: "Maruti Suzuki India Ltd", sector: "Auto" },
  { name: "HCLTECH", fullName: "HCL Technologies Ltd", sector: "IT" },
  { name: "SUNPHARMA", fullName: "Sun Pharmaceutical Ltd", sector: "Pharma" },
  { name: "TATAMOTORS", fullName: "Tata Motors Ltd", sector: "Auto" },
  { name: "TITAN", fullName: "Titan Company Ltd", sector: "Consumer" },
  { name: "BAJAJFINSV", fullName: "Bajaj Finserv Ltd", sector: "Finance" },
  { name: "NESTLEIND", fullName: "Nestle India Ltd", sector: "FMCG" },
  { name: "ONGC", fullName: "Oil & Natural Gas Corp Ltd", sector: "Energy" },
  { name: "NTPC", fullName: "NTPC Ltd", sector: "Power" },
  { name: "POWERGRID", fullName: "Power Grid Corp Ltd", sector: "Power" },
  { name: "TATASTEEL", fullName: "Tata Steel Ltd", sector: "Metals" },
  { name: "ULTRACEMCO", fullName: "UltraTech Cement Ltd", sector: "Cement" },
  { name: "TECHM", fullName: "Tech Mahindra Ltd", sector: "IT" },
  { name: "M&M", fullName: "Mahindra & Mahindra Ltd", sector: "Auto" },
  { name: "JSWSTEEL", fullName: "JSW Steel Ltd", sector: "Metals" },
  { name: "ADANIENT", fullName: "Adani Enterprises Ltd", sector: "Diversified" },
  { name: "ADANIPORTS", fullName: "Adani Ports & SEZ Ltd", sector: "Infrastructure" },
  { name: "COALINDIA", fullName: "Coal India Ltd", sector: "Mining" },
  { name: "DRREDDY", fullName: "Dr Reddy's Laboratories Ltd", sector: "Pharma" },
  { name: "CIPLA", fullName: "Cipla Ltd", sector: "Pharma" },
  { name: "GRASIM", fullName: "Grasim Industries Ltd", sector: "Cement" },
  { name: "DIVISLAB", fullName: "Divi's Laboratories Ltd", sector: "Pharma" },
  { name: "EICHERMOT", fullName: "Eicher Motors Ltd", sector: "Auto" },
  { name: "HEROMOTOCO", fullName: "Hero MotoCorp Ltd", sector: "Auto" },
  { name: "BPCL", fullName: "Bharat Petroleum Corp Ltd", sector: "Energy" },
  { name: "TATAPOWER", fullName: "Tata Power Company Ltd", sector: "Power" },
  { name: "KPITTECH", fullName: "KPIT Technologies Ltd", sector: "IT" },
  { name: "QUICKHEAL", fullName: "Quick Heal Technologies Ltd", sector: "IT" },
  { name: "HUL", fullName: "Hindustan Unilever Ltd", sector: "FMCG" },
  { name: "APOLLOHOSP", fullName: "Apollo Hospitals Enterprise Ltd", sector: "Healthcare" },
  { name: "BRITANNIA", fullName: "Britannia Industries Ltd", sector: "FMCG" },
  { name: "INDUSINDBK", fullName: "IndusInd Bank Ltd", sector: "Banking" },
  { name: "SGBMAY29", fullName: "Sovereign Gold Bond May 2029", sector: "Gold" },
  { name: "HINDALCO", fullName: "Hindalco Industries Ltd", sector: "Metals" },
  { name: "VEDL", fullName: "Vedanta Ltd", sector: "Metals" },
  { name: "ZOMATO", fullName: "Zomato Ltd", sector: "Consumer" },
  { name: "PAYTM", fullName: "One97 Communications Ltd", sector: "Fintech" },
  { name: "NYKAA", fullName: "FSN E-Commerce Ventures Ltd", sector: "Consumer" },
  { name: "DELHIVERY", fullName: "Delhivery Ltd", sector: "Logistics" },
  { name: "IRCTC", fullName: "Indian Railway Catering & Tourism Corp", sector: "Travel" },
  { name: "TRENT", fullName: "Trent Ltd", sector: "Retail" },
  { name: "JUBLFOOD", fullName: "Jubilant FoodWorks Ltd", sector: "Consumer" },
  { name: "EVEREADY", fullName: "Eveready Industries India Ltd", sector: "Consumer" },
  { name: "PIDILITIND", fullName: "Pidilite Industries Ltd", sector: "Chemicals" },
  { name: "DABUR", fullName: "Dabur India Ltd", sector: "FMCG" },
  { name: "GODREJCP", fullName: "Godrej Consumer Products Ltd", sector: "FMCG" },
  { name: "HAVELLS", fullName: "Havells India Ltd", sector: "Consumer Durables" },
  { name: "VOLTAS", fullName: "Voltas Ltd", sector: "Consumer Durables" },
  { name: "BIOCON", fullName: "Biocon Ltd", sector: "Pharma" },
  { name: "LUPIN", fullName: "Lupin Ltd", sector: "Pharma" },
  { name: "AUROPHARMA", fullName: "Aurobindo Pharma Ltd", sector: "Pharma" },
];

module.exports = { STOCKS_LIST };
